export const ADD_NUM = 'ADD_NUM'
export const ADD_SIGN = 'ADD_SIGN'
export const CLEAR_SIGNS = 'CLEAR_SIGNS'
export const CLEAR_LAST = 'CLEAR_LAST'
export const SET_RES = 'SET_RES'
export const ADD_OPEN_BRACKET = 'ADD_OPEN_BRACKET'
export const ADD_CLOSE_BRACKET = 'ADD_CLOSE_BRACKET'